#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef BLUESTSDK_GUI_SWIFT_H
#define BLUESTSDK_GUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import BlueSTSDK;
@import CoreFoundation;
@import CoreNFC;
@import Foundation;
@import MessageUI;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlueSTSDK_Gui",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC13BlueSTSDK_Gui16BaseSubtitleCell")
@interface BaseSubtitleCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui17BaseTableViewCell")
@interface BaseTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui8BaseView")
@interface BaseView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end

@class UIWebView;
@class NSURLRequest;
@class UIStoryboardSegue;
@class NSBundle;

SWIFT_CLASS("_TtC13BlueSTSDK_Gui28BlueSTSDKAboutViewController")
@interface BlueSTSDKAboutViewController : UIViewController <UIWebViewDelegate>
- (void)viewDidLoad;
/// if a link is pressed open the broweser to display it
/// \param webView <#webView description#>
///
/// \param request <#request description#>
///
/// \param navigationType <#navigationType description#>
///
///
/// returns:
/// <#return value description#>
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class NSURL;
@class BlueSTSDKLibLicense;

SWIFT_PROTOCOL("_TtP13BlueSTSDK_Gui36BlueSTSDKAboutViewControllerDelegate_")
@protocol BlueSTSDKAboutViewControllerDelegate
/// page to show as main content of the page
///
/// returns:
/// path of an html file or nil if not needed
- (NSString * _Nullable)abaoutHtmlPagePath SWIFT_WARN_UNUSED_RESULT;
/// image to show on the top of the view
///
/// returns:
/// image to show on the top or nil if not needed
- (UIImage * _Nullable)headImage SWIFT_WARN_UNUSED_RESULT;
/// display the menu with the privacy information
///
/// returns:
/// url where fine the privacy information
- (NSURL * _Nullable)privacyInfoUrl SWIFT_WARN_UNUSED_RESULT;
/// display the menu with the license of the third party
///
/// returns:
/// list of infos about the third party libraries, nil if not needed
- (NSArray<BlueSTSDKLibLicense *> * _Nullable)libLicenseInfo SWIFT_WARN_UNUSED_RESULT;
@end

@class BlueSTSDKDebug;
@class NSNotification;

SWIFT_CLASS("_TtC13BlueSTSDK_Gui35BlueSTSDKDebugConsoleViewController")
@interface BlueSTSDKDebugConsoleViewController : UIViewController
@property (nonatomic, strong) BlueSTSDKDebug * _Null_unspecified console;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)resizeConsoleOnKeyboardShow:(NSNotification * _Nonnull)n;
- (void)resizeConsoleOnKeyboardHide:(NSNotification * _Nonnull)n;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

@interface BlueSTSDKDebugConsoleViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


@interface BlueSTSDKDebugConsoleViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKDebugOutputDelegate>
- (void)debug:(BlueSTSDKDebug * _Nonnull)debug didStdOutReceived:(NSString * _Nonnull)msg;
- (void)debug:(BlueSTSDKDebug * _Nonnull)debug didStdErrReceived:(NSString * _Nonnull)msg;
- (void)debug:(BlueSTSDKDebug * _Nonnull)debug didStdInSend:(NSString * _Nonnull)msg error:(NSError * _Nullable)error;
@end

@class UIBarButtonItem;

SWIFT_CLASS("_TtC13BlueSTSDK_Gui27BlueSTSDKDemoViewController")
@interface BlueSTSDKDemoViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)showPopupMenu:(UIBarButtonItem * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class BlueSTSDKNode;

@interface BlueSTSDKDemoViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKNodeStateDelegate>
- (void)node:(BlueSTSDKNode * _Nonnull)node didChangeState:(BlueSTSDKNodeState)newState prevState:(BlueSTSDKNodeState)prevState;
@end

@class UIAlertAction;

SWIFT_PROTOCOL("_TtP13BlueSTSDK_Gui35BlueSTSDKViewControllerMenuDelegate_")
@protocol BlueSTSDKViewControllerMenuDelegate
/// Append the action at the end of the menu
- (void)addMenuAction:(UIAlertAction * _Nonnull)action;
/// insert the action into a specific position
- (void)addMenuAction:(UIAlertAction * _Nonnull)action atIndex:(NSInteger)index;
/// remove the action from the menu
- (void)removeMenuAction:(UIAlertAction * _Nonnull)action;
/// return the number of items in the menu
@property (nonatomic, readonly) NSInteger menuActionCount;
- (void)addBarButton:(UIBarButtonItem * _Nonnull)item;
- (void)removeBarButton:(UIBarButtonItem * _Nonnull)item;
@end


@interface BlueSTSDKDemoViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKViewControllerMenuDelegate>
- (void)addBarButton:(UIBarButtonItem * _Nonnull)item;
- (void)removeBarButton:(UIBarButtonItem * _Nonnull)item;
- (void)addMenuAction:(UIAlertAction * _Nonnull)action;
- (void)addMenuAction:(UIAlertAction * _Nonnull)action atIndex:(NSInteger)index;
- (void)removeMenuAction:(UIAlertAction * _Nonnull)action;
@property (nonatomic, readonly) NSInteger menuActionCount;
@end

@class MFMailComposeViewController;

@interface BlueSTSDKDemoViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <MFMailComposeViewControllerDelegate>
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
@end


SWIFT_PROTOCOL("_TtP13BlueSTSDK_Gui25BlueSTSDKDemoViewProtocol_")
@protocol BlueSTSDKDemoViewProtocol
@property (nonatomic, strong) BlueSTSDKNode * _Null_unspecified node;
@property (nonatomic, strong) id <BlueSTSDKViewControllerMenuDelegate> _Nullable menuDelegate;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui29BlueSTSDKDemoViewProtocolUtil")
@interface BlueSTSDKDemoViewProtocolUtil : NSObject
+ (void)setupDemoProtocolWithDemo:(UIViewController * _Nonnull)demo node:(BlueSTSDKNode * _Nonnull)node menuDelegate:(id <BlueSTSDKViewControllerMenuDelegate> _Nullable)menuDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionDownloadTask;
@class NSURLSessionTask;

/// class to display the download progress
SWIFT_CLASS("_TtC13BlueSTSDK_Gui35BlueSTSDKDownloadFileViewController")
@interface BlueSTSDKDownloadFileViewController : NSObject <NSURLSessionDownloadDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didWriteData:(int64_t)bytesWritten totalBytesWritten:(int64_t)totalBytesWritten totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui39BlueSTSDKFwUpgradeManagerViewController")
@interface BlueSTSDKFwUpgradeManagerViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIDocumentPickerViewController;

@interface BlueSTSDKFwUpgradeManagerViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UIDocumentPickerDelegate>
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)pickController didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)pickController didPickDocumentAtURL:(NSURL * _Nonnull)url;
@end



/// Class that contains the license name and the path with the library license file
SWIFT_CLASS("_TtC13BlueSTSDK_Gui19BlueSTSDKLibLicense")
@interface BlueSTSDKLibLicense : NSObject
/// create an object
/// \param name library name
///
/// \param licenseFile license location
///
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name licenseFile:(NSString * _Nonnull)licenseFile OBJC_DESIGNATED_INITIALIZER;
/// create an object, the license name is the file name that contains the licenses
/// \param licenseFile path with the license
///
- (nonnull instancetype)initWithLicenseFile:(NSString * _Nonnull)licenseFile OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Display the file content
SWIFT_CLASS("_TtC13BlueSTSDK_Gui40BlueSTSDKLibLicenseDetailsViewController")
@interface BlueSTSDKLibLicenseDetailsViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;

/// class showing a list of license used by the application
SWIFT_CLASS("_TtC13BlueSTSDK_Gui33BlueSTSDKLibLicenseViewController")
@interface BlueSTSDKLibLicenseViewController : UITableViewController
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView accessoryButtonTappedForRowWithIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class UIButton;

SWIFT_CLASS("_TtC13BlueSTSDK_Gui27BlueSTSDKMainViewController")
@interface BlueSTSDKMainViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified mAppNameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified mAppVersionLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified mAboutButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified mNodeListButton;
- (void)viewDidLoad;
/// <ul>
///   <li>
///     Hide the navigation bar for keep space for the search button in small devices
///   </li>
///   <li>
///   </li>
///   <li>
///     @param animated true if the system is doing an animation
///   </li>
/// </ul>
- (void)viewWillAppear:(BOOL)animated;
/// <ul>
///   <li>
///     Show the navigation bar for the next view
///   </li>
///   <li>
///   </li>
///   <li>
///     @param animated true if the system is doing an animation
///   </li>
/// </ul>
- (void)viewWillDisappear:(BOOL)animated;
- (IBAction)onAboutClick:(UIButton * _Nonnull)sender;
- (IBAction)onStartDiscoveryClick:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13BlueSTSDK_Gui25BlueSTSDKNodeListViewCell")
@interface BlueSTSDKNodeListViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui31BlueSTSDKNodeListViewController")
@interface BlueSTSDKNodeListViewController : UITableViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
/// Call local DB and retrieve BlueSTSDK v2 firmwares,
/// start the discovery process,  when the view is shown,
/// we close the connection with all the previous discovered nodes
- (void)viewDidAppear:(BOOL)animated;
/// when the view change we stop the discovering process
/// @param animated <#animated description#>
- (void)viewWillDisappear:(BOOL)animated;
/// function called each time the user click in the uibarbutton,
/// it change the status of the discovery
- (void)manageDiscoveryButton;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
/// pass the deleage to the next view controler
/// @param segue  storyboard segue
/// @param sender view that start the change
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class BlueSTSDKManager;

@interface BlueSTSDKNodeListViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKManagerDelegate>
- (void)manager:(BlueSTSDKManager * _Nonnull)manager didDiscoverNode:(BlueSTSDKNode * _Nonnull)node;
- (void)manager:(BlueSTSDKManager * _Nonnull)manager didChangeDiscovery:(BOOL)enable;
@end


@class NFCNDEFReaderSession;
@class NFCNDEFMessage;

@interface BlueSTSDKNodeListViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <NFCNDEFReaderSessionDelegate>
- (void)readerSession:(NFCNDEFReaderSession * _Nonnull)session didInvalidateWithError:(NSError * _Nonnull)error;
- (void)readerSession:(NFCNDEFReaderSession * _Nonnull)session didDetectNDEFs:(NSArray<NFCNDEFMessage *> * _Nonnull)messages;
@end


SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface BlueSTSDKNodeListViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UIDocumentPickerDelegate>
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)pickController didPickDocumentAtURL:(NSURL * _Nonnull)url;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)pickController didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
@end


@interface BlueSTSDKNodeListViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKNodeStateDelegate>
- (void)node:(BlueSTSDKNode * _Nonnull)node didChangeState:(BlueSTSDKNodeState)newState prevState:(BlueSTSDKNodeState)prevState;
@end

@class BlueSTSDKFeatureField;
@class NSData;
@class BlueSTSDKExtractResult;

/// write feature used to control the file upload
SWIFT_CLASS("_TtC13BlueSTSDK_Gui33BlueSTSDKSTM32WBOTAControlFeature")
@interface BlueSTSDKSTM32WBOTAControlFeature : BlueSTSDKFeature
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// feature where wait a notification before the board will reboot with the new feature
SWIFT_CLASS("_TtC13BlueSTSDK_Gui36BlueSTSDKSTM32WBOTAWillRebootFeature")
@interface BlueSTSDKSTM32WBOTAWillRebootFeature : BlueSTSDKDeviceTimestampFeature
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// write feature that will upload the file to the board
SWIFT_CLASS("_TtC13BlueSTSDK_Gui32BlueSTSDKSTM32WBOtaUploadFeature")
@interface BlueSTSDKSTM32WBOtaUploadFeature : BlueSTSDKFeature
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// Write feature that will rebot the board in ota mode
SWIFT_CLASS("_TtC13BlueSTSDK_Gui36BlueSTSDKSTM32WBRebootOtaModeFeature")
@interface BlueSTSDKSTM32WBRebootOtaModeFeature : BlueSTSDKFeature
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// View controller with a progress bar while searching the ota node,
/// when the node is found we connect and move to the fw upgrade view controller
SWIFT_CLASS("_TtC13BlueSTSDK_Gui35BlueSTSDKSeachOtaNodeViewController")
@interface BlueSTSDKSeachOtaNodeViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface BlueSTSDKSeachOtaNodeViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKNodeStateDelegate>
- (void)node:(BlueSTSDKNode * _Nonnull)node didChangeState:(BlueSTSDKNodeState)newState prevState:(BlueSTSDKNodeState)prevState;
@end


@interface BlueSTSDKSeachOtaNodeViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKManagerDelegate>
- (void)manager:(BlueSTSDKManager * _Nonnull)manager didDiscoverNode:(BlueSTSDKNode * _Nonnull)node;
- (void)manager:(BlueSTSDKManager * _Nonnull)manager didChangeDiscovery:(BOOL)enable;
@end




SWIFT_CLASS("_TtC13BlueSTSDK_Gui13DocumentSaver")
@interface DocumentSaver : NSObject <UIDocumentPickerDelegate>
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController * _Nonnull)controller;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui16DocumentSelector")
@interface DocumentSelector : NSObject <UIDocumentPickerDelegate>
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController * _Nonnull)controller;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui19FwCatalogAutoUpdate")
@interface FwCatalogAutoUpdate : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface FwCatalogAutoUpdate (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface FwCatalogAutoUpdate (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui11LoadingView")
@interface LoadingView : BaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui25STM32WBAOtaViewController")
@interface STM32WBAOtaViewController : UIViewController <BlueSTSDKDemoViewProtocol>
@property (nonatomic, strong) BlueSTSDKNode * _Null_unspecified node;
@property (nonatomic, strong) id <BlueSTSDKViewControllerMenuDelegate> _Nullable menuDelegate;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface STM32WBAOtaViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UIDocumentPickerDelegate>
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)pickController didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
@end



/// Write feature used to switch on and off the board led
SWIFT_CLASS("_TtC13BlueSTSDK_Gui24STM32WBControlLedFeature")
@interface STM32WBControlLedFeature : BlueSTSDKFeature
/// build the feature to change the led status
/// \param node node where the led will change
///
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// View Controller that will periodically (every 2 seconds) request and display the rssi value
SWIFT_CLASS("_TtC13BlueSTSDK_Gui31STM32WBRSSIUpdateViewController")
@interface STM32WBRSSIUpdateViewController : UIViewController <BlueSTSDKDemoViewProtocol>
/// node where query the rssi
@property (nonatomic, strong) BlueSTSDKNode * _Null_unspecified node;
@property (nonatomic, strong) id <BlueSTSDKViewControllerMenuDelegate> _Nullable menuDelegate;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// View Controller to switch on and off a led in a specific node
SWIFT_CLASS("_TtC13BlueSTSDK_Gui30STM32WBLedButtonViewController")
@interface STM32WBLedButtonViewController : STM32WBRSSIUpdateViewController
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class BlueSTSDKFeatureSample;

@interface STM32WBLedButtonViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKFeatureDelegate>
/// Call when the button is pressed in the board
/// \param feature feature that trigger the event
///
/// \param sample feature data
///
- (void)didUpdateFeature:(BlueSTSDKFeature * _Nonnull)feature sample:(BlueSTSDKFeatureSample * _Nonnull)sample;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui31STM32WBLedNetworkViewController")
@interface STM32WBLedNetworkViewController : STM32WBRSSIUpdateViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface STM32WBLedNetworkViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKFeatureDelegate>
/// called when a ble notification arrive, this method will call the proper method
/// \param feature <#feature description#>
///
/// \param sample <#sample description#>
///
- (void)didUpdateFeature:(BlueSTSDKFeature * _Nonnull)feature sample:(BlueSTSDKFeatureSample * _Nonnull)sample;
@end


@interface STM32WBLedNetworkViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


/// Feature used to know the device connected in the network, the network can contain at maximum 6
/// devices, for each device you can query if it is connected or not.
SWIFT_CLASS("_TtC13BlueSTSDK_Gui27STM32WBNetworkStatusFeature")
@interface STM32WBNetworkStatusFeature : BlueSTSDKDeviceTimestampFeature
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


/// Write feature used to switch on and off the board led
SWIFT_CLASS("_TtC13BlueSTSDK_Gui33STM32WBProtocolRadioRebootFeature")
@interface STM32WBProtocolRadioRebootFeature : BlueSTSDKFeature
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end



@interface STM32WBRSSIUpdateViewController (SWIFT_EXTENSION(BlueSTSDK_Gui)) <BlueSTSDKNodeBleConnectionParamDelegate>
/// Function called when a new rssi is available
/// \param node node that upgrade the node
///
/// \param newRssi new rssi value
///
- (void)node:(BlueSTSDKNode * _Nonnull)node didChangeRssi:(NSInteger)newRssi;
@end


/// Class used to notify the switch change status
SWIFT_CLASS("_TtC13BlueSTSDK_Gui26STM32WBSwitchStatusFeature")
@interface STM32WBSwitchStatusFeature : BlueSTSDKDeviceTimestampFeature
- (NSArray<BlueSTSDKFeatureField *> * _Nonnull)getFieldsDesc SWIFT_WARN_UNUSED_RESULT;
/// Build a switch status feature
/// \param node node that will send data to this feature
///
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
/// extract the feature data from the notification
/// \param timestamp event timestamp
///
/// \param data notification bytes
///
/// \param offset byte offset where the valid data starts
///
///
/// returns:
/// extracted data and byte read
- (BlueSTSDKExtractResult * _Nonnull)extractData:(uint64_t)timestamp data:(NSData * _Nonnull)data dataOffset:(uint32_t)offset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWhitNode:(BlueSTSDKNode * _Nonnull)node name:(NSString * _Nonnull)name SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13BlueSTSDK_Gui13TitleIconView")
@interface TitleIconView : BaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end












@interface UITextView (SWIFT_EXTENSION(BlueSTSDK_Gui)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end









@interface UIViewController (SWIFT_EXTENSION(BlueSTSDK_Gui))
- (void)changeViewController:(UIViewController * _Nonnull)newView;
- (void)showAllertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message closeController:(BOOL)closeController;
- (void)showErrorMsg:(NSString * _Nonnull)msg title:(NSString * _Nonnull)title closeController:(BOOL)closeController SWIFT_DEPRECATED;
@end


#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
